INSERT INTO marveledges_test VALUES ('Iron Man', 'Fantastic Four', 42117);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Hawkeye', 42117);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Iron Fist', 42117);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Magneto', 42117);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Doctor Strange', 42117);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Hulk', 42117);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Doctor Octopus', 42117);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Daredevil', 42117);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Lizard', 42117);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Loki', 42117);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Captain America', 42117);
INSERT INTO marveledges_test VALUES ('Fantastic Four', 'Hawkeye', 42117);
INSERT INTO marveledges_test VALUES ('Fantastic Four', 'Iron Fist', 42117);
INSERT INTO marveledges_test VALUES ('Fantastic Four', 'Magneto', 42117);
INSERT INTO marveledges_test VALUES ('Fantastic Four', 'Doctor Strange', 42117);
INSERT INTO marveledges_test VALUES ('Fantastic Four', 'Hulk', 42117);
INSERT INTO marveledges_test VALUES ('Fantastic Four', 'Doctor Octopus', 42117);
INSERT INTO marveledges_test VALUES ('Fantastic Four', 'Daredevil', 42117);
INSERT INTO marveledges_test VALUES ('Fantastic Four', 'Lizard', 42117);
INSERT INTO marveledges_test VALUES ('Fantastic Four', 'Loki', 42117);
INSERT INTO marveledges_test VALUES ('Fantastic Four', 'Captain America', 42117);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Iron Fist', 42117);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Magneto', 42117);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Doctor Strange', 42117);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Hulk', 42117);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Doctor Octopus', 42117);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Daredevil', 42117);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Lizard', 42117);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Loki', 42117);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Captain America', 42117);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Magneto', 42117);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Doctor Strange', 42117);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Hulk', 42117);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Doctor Octopus', 42117);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Daredevil', 42117);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Lizard', 42117);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Loki', 42117);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Captain America', 42117);
INSERT INTO marveledges_test VALUES ('Magneto', 'Doctor Strange', 42117);
INSERT INTO marveledges_test VALUES ('Magneto', 'Hulk', 42117);
INSERT INTO marveledges_test VALUES ('Magneto', 'Doctor Octopus', 42117);
INSERT INTO marveledges_test VALUES ('Magneto', 'Daredevil', 42117);
INSERT INTO marveledges_test VALUES ('Magneto', 'Lizard', 42117);
INSERT INTO marveledges_test VALUES ('Magneto', 'Loki', 42117);
INSERT INTO marveledges_test VALUES ('Magneto', 'Captain America', 42117);
INSERT INTO marveledges_test VALUES ('Doctor Strange', 'Hulk', 42117);
INSERT INTO marveledges_test VALUES ('Doctor Strange', 'Doctor Octopus', 42117);
INSERT INTO marveledges_test VALUES ('Doctor Strange', 'Daredevil', 42117);
INSERT INTO marveledges_test VALUES ('Doctor Strange', 'Lizard', 42117);
INSERT INTO marveledges_test VALUES ('Doctor Strange', 'Loki', 42117);
INSERT INTO marveledges_test VALUES ('Doctor Strange', 'Captain America', 42117);
INSERT INTO marveledges_test VALUES ('Hulk', 'Doctor Octopus', 42117);
INSERT INTO marveledges_test VALUES ('Hulk', 'Daredevil', 42117);
INSERT INTO marveledges_test VALUES ('Hulk', 'Lizard', 42117);
INSERT INTO marveledges_test VALUES ('Hulk', 'Loki', 42117);
INSERT INTO marveledges_test VALUES ('Hulk', 'Captain America', 42117);
INSERT INTO marveledges_test VALUES ('Doctor Octopus', 'Daredevil', 42117);
INSERT INTO marveledges_test VALUES ('Doctor Octopus', 'Lizard', 42117);
INSERT INTO marveledges_test VALUES ('Doctor Octopus', 'Loki', 42117);
INSERT INTO marveledges_test VALUES ('Doctor Octopus', 'Captain America', 42117);
INSERT INTO marveledges_test VALUES ('Daredevil', 'Lizard', 42117);
INSERT INTO marveledges_test VALUES ('Daredevil', 'Loki', 42117);
INSERT INTO marveledges_test VALUES ('Daredevil', 'Captain America', 42117);
INSERT INTO marveledges_test VALUES ('Lizard', 'Loki', 42117);
INSERT INTO marveledges_test VALUES ('Lizard', 'Captain America', 42117);
INSERT INTO marveledges_test VALUES ('Loki', 'Captain America', 42117);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Spider-Man', 41094);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Hulk', 41094);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Thor', 41094);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Wolverine', 41094);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Hawkeye', 41094);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Captain America', 41094);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Hulk', 41094);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Thor', 41094);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Wolverine', 41094);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Hawkeye', 41094);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Captain America', 41094);
INSERT INTO marveledges_test VALUES ('Hulk', 'Thor', 41094);
INSERT INTO marveledges_test VALUES ('Hulk', 'Wolverine', 41094);
INSERT INTO marveledges_test VALUES ('Hulk', 'Hawkeye', 41094);
INSERT INTO marveledges_test VALUES ('Hulk', 'Captain America', 41094);
INSERT INTO marveledges_test VALUES ('Thor', 'Wolverine', 41094);
INSERT INTO marveledges_test VALUES ('Thor', 'Hawkeye', 41094);
INSERT INTO marveledges_test VALUES ('Thor', 'Captain America', 41094);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Hawkeye', 41094);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Captain America', 41094);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Captain America', 41094);
INSERT INTO marveledges_test VALUES ('Wolverine', 'X-Men', 41122);
INSERT INTO marveledges_test VALUES ('Emma Frost', 'X-Men', 40154);
INSERT INTO marveledges_test VALUES ('Emma Frost', 'Cyclops', 40154);
INSERT INTO marveledges_test VALUES ('X-Men', 'Cyclops', 40154);
INSERT INTO marveledges_test VALUES ('Odin', 'Thor', 41108);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Vulture', 35511);
INSERT INTO marveledges_test VALUES ('Thing', 'Spider-Man', 35509);
INSERT INTO marveledges_test VALUES ('Thing', 'Wolverine', 35509);
INSERT INTO marveledges_test VALUES ('Thing', 'Hawkeye', 35509);
INSERT INTO marveledges_test VALUES ('Thing', 'Mockingbird', 35509);
INSERT INTO marveledges_test VALUES ('Thing', 'Invisible Woman', 35509);
INSERT INTO marveledges_test VALUES ('Thing', 'Dragon Man', 35509);
INSERT INTO marveledges_test VALUES ('Thing', 'Avengers', 35509);
INSERT INTO marveledges_test VALUES ('Thing', 'Leech', 35509);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Wolverine', 35509);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Hawkeye', 35509);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Mockingbird', 35509);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Invisible Woman', 35509);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Dragon Man', 35509);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Avengers', 35509);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Leech', 35509);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Hawkeye', 35509);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Mockingbird', 35509);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Invisible Woman', 35509);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Dragon Man', 35509);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Avengers', 35509);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Leech', 35509);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Mockingbird', 35509);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Invisible Woman', 35509);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Dragon Man', 35509);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Avengers', 35509);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Leech', 35509);
INSERT INTO marveledges_test VALUES ('Mockingbird', 'Invisible Woman', 35509);
INSERT INTO marveledges_test VALUES ('Mockingbird', 'Dragon Man', 35509);
INSERT INTO marveledges_test VALUES ('Mockingbird', 'Avengers', 35509);
INSERT INTO marveledges_test VALUES ('Mockingbird', 'Leech', 35509);
INSERT INTO marveledges_test VALUES ('Invisible Woman', 'Dragon Man', 35509);
INSERT INTO marveledges_test VALUES ('Invisible Woman', 'Avengers', 35509);
INSERT INTO marveledges_test VALUES ('Invisible Woman', 'Leech', 35509);
INSERT INTO marveledges_test VALUES ('Dragon Man', 'Avengers', 35509);
INSERT INTO marveledges_test VALUES ('Dragon Man', 'Leech', 35509);
INSERT INTO marveledges_test VALUES ('Avengers', 'Leech', 35509);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Spider-Man', 35225);
INSERT INTO marveledges_test VALUES ('Iron Man', 'M', 35225);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Wolverine', 35225);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Captain America', 35225);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Avengers', 35225);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'M', 35225);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Wolverine', 35225);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Captain America', 35225);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Avengers', 35225);
INSERT INTO marveledges_test VALUES ('M', 'Wolverine', 35225);
INSERT INTO marveledges_test VALUES ('M', 'Captain America', 35225);
INSERT INTO marveledges_test VALUES ('M', 'Avengers', 35225);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Captain America', 35225);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Avengers', 35225);
INSERT INTO marveledges_test VALUES ('Captain America', 'Avengers', 35225);
INSERT INTO marveledges_test VALUES ('Iron Man', 'Odin', 38978);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'M', 35246);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Hulk', 35246);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Avengers', 35246);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Viper', 35246);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Gorgon', 35246);
INSERT INTO marveledges_test VALUES ('M', 'Hulk', 35246);
INSERT INTO marveledges_test VALUES ('M', 'Avengers', 35246);
INSERT INTO marveledges_test VALUES ('M', 'Viper', 35246);
INSERT INTO marveledges_test VALUES ('M', 'Gorgon', 35246);
INSERT INTO marveledges_test VALUES ('Hulk', 'Avengers', 35246);
INSERT INTO marveledges_test VALUES ('Hulk', 'Viper', 35246);
INSERT INTO marveledges_test VALUES ('Hulk', 'Gorgon', 35246);
INSERT INTO marveledges_test VALUES ('Avengers', 'Viper', 35246);
INSERT INTO marveledges_test VALUES ('Avengers', 'Gorgon', 35246);
INSERT INTO marveledges_test VALUES ('Viper', 'Gorgon', 35246);
INSERT INTO marveledges_test VALUES ('Wolverine', 'X-Men', 38586);
INSERT INTO marveledges_test VALUES ('X-Men', 'Cyclops', 37942);
INSERT INTO marveledges_test VALUES ('X-Men', 'Iceman', 37942);
INSERT INTO marveledges_test VALUES ('Cyclops', 'Iceman', 37942);
INSERT INTO marveledges_test VALUES ('Avengers', 'Captain America', 41524);
INSERT INTO marveledges_test VALUES ('Magneto', 'Rogue', 39481);
INSERT INTO marveledges_test VALUES ('Magneto', 'X-Men', 39481);
INSERT INTO marveledges_test VALUES ('Rogue', 'X-Men', 39481);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Beast', 35296);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Iceman', 35296);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Sabretooth', 35296);
INSERT INTO marveledges_test VALUES ('Wolverine', 'X-Force', 35296);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Nightcrawler', 35296);
INSERT INTO marveledges_test VALUES ('Beast', 'Iceman', 35296);
INSERT INTO marveledges_test VALUES ('Beast', 'Sabretooth', 35296);
INSERT INTO marveledges_test VALUES ('Beast', 'X-Force', 35296);
INSERT INTO marveledges_test VALUES ('Beast', 'Nightcrawler', 35296);
INSERT INTO marveledges_test VALUES ('Iceman', 'Sabretooth', 35296);
INSERT INTO marveledges_test VALUES ('Iceman', 'X-Force', 35296);
INSERT INTO marveledges_test VALUES ('Iceman', 'Nightcrawler', 35296);
INSERT INTO marveledges_test VALUES ('Sabretooth', 'X-Force', 35296);
INSERT INTO marveledges_test VALUES ('Sabretooth', 'Nightcrawler', 35296);
INSERT INTO marveledges_test VALUES ('X-Force', 'Nightcrawler', 35296);
INSERT INTO marveledges_test VALUES ('Jubilee', 'X-Men', 41450);
INSERT INTO marveledges_test VALUES ('Jubilee', 'War Machine', 41450);
INSERT INTO marveledges_test VALUES ('Jubilee', 'Domino', 41450);
INSERT INTO marveledges_test VALUES ('Jubilee', 'Colossus', 41450);
INSERT INTO marveledges_test VALUES ('Jubilee', 'Warpath', 41450);
INSERT INTO marveledges_test VALUES ('Jubilee', 'Storm', 41450);
INSERT INTO marveledges_test VALUES ('X-Men', 'War Machine', 41450);
INSERT INTO marveledges_test VALUES ('X-Men', 'Domino', 41450);
INSERT INTO marveledges_test VALUES ('X-Men', 'Colossus', 41450);
INSERT INTO marveledges_test VALUES ('X-Men', 'Warpath', 41450);
INSERT INTO marveledges_test VALUES ('X-Men', 'Storm', 41450);
INSERT INTO marveledges_test VALUES ('War Machine', 'Domino', 41450);
INSERT INTO marveledges_test VALUES ('War Machine', 'Colossus', 41450);
INSERT INTO marveledges_test VALUES ('War Machine', 'Warpath', 41450);
INSERT INTO marveledges_test VALUES ('War Machine', 'Storm', 41450);
INSERT INTO marveledges_test VALUES ('Domino', 'Colossus', 41450);
INSERT INTO marveledges_test VALUES ('Domino', 'Warpath', 41450);
INSERT INTO marveledges_test VALUES ('Domino', 'Storm', 41450);
INSERT INTO marveledges_test VALUES ('Colossus', 'Warpath', 41450);
INSERT INTO marveledges_test VALUES ('Colossus', 'Storm', 41450);
INSERT INTO marveledges_test VALUES ('Warpath', 'Storm', 41450);
INSERT INTO marveledges_test VALUES ('Magneto', 'Rogue', 41453);
INSERT INTO marveledges_test VALUES ('Magneto', 'Gambit', 41453);
INSERT INTO marveledges_test VALUES ('Magneto', 'X-Men', 41453);
INSERT INTO marveledges_test VALUES ('Rogue', 'Gambit', 41453);
INSERT INTO marveledges_test VALUES ('Rogue', 'X-Men', 41453);
INSERT INTO marveledges_test VALUES ('Gambit', 'X-Men', 41453);
INSERT INTO marveledges_test VALUES ('Avengers', 'Captain America', 35130);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Cobra', 41121);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Spider-Man', 41129);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'M', 41129);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Wolverine', 41129);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Thing', 41129);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Mockingbird', 41129);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Doctor Strange', 41129);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Cage', 41129);
INSERT INTO marveledges_test VALUES ('Iron Fist', 'Avengers', 41129);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'M', 41129);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Wolverine', 41129);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Thing', 41129);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Mockingbird', 41129);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Doctor Strange', 41129);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Cage', 41129);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Avengers', 41129);
INSERT INTO marveledges_test VALUES ('M', 'Wolverine', 41129);
INSERT INTO marveledges_test VALUES ('M', 'Thing', 41129);
INSERT INTO marveledges_test VALUES ('M', 'Mockingbird', 41129);
INSERT INTO marveledges_test VALUES ('M', 'Doctor Strange', 41129);
INSERT INTO marveledges_test VALUES ('M', 'Cage', 41129);
INSERT INTO marveledges_test VALUES ('M', 'Avengers', 41129);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Thing', 41129);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Mockingbird', 41129);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Doctor Strange', 41129);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Cage', 41129);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Avengers', 41129);
INSERT INTO marveledges_test VALUES ('Thing', 'Mockingbird', 41129);
INSERT INTO marveledges_test VALUES ('Thing', 'Doctor Strange', 41129);
INSERT INTO marveledges_test VALUES ('Thing', 'Cage', 41129);
INSERT INTO marveledges_test VALUES ('Thing', 'Avengers', 41129);
INSERT INTO marveledges_test VALUES ('Mockingbird', 'Doctor Strange', 41129);
INSERT INTO marveledges_test VALUES ('Mockingbird', 'Cage', 41129);
INSERT INTO marveledges_test VALUES ('Mockingbird', 'Avengers', 41129);
INSERT INTO marveledges_test VALUES ('Doctor Strange', 'Cage', 41129);
INSERT INTO marveledges_test VALUES ('Doctor Strange', 'Avengers', 41129);
INSERT INTO marveledges_test VALUES ('Cage', 'Avengers', 41129);
INSERT INTO marveledges_test VALUES ('Wolverine', 'X-Men', 40068);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Cyclops', 40068);
INSERT INTO marveledges_test VALUES ('X-Men', 'Cyclops', 40068);
INSERT INTO marveledges_test VALUES ('X-Men', 'Death', 36153);
INSERT INTO marveledges_test VALUES ('X-Men', 'Force', 36153);
INSERT INTO marveledges_test VALUES ('X-Men', 'Wolverine', 36153);
INSERT INTO marveledges_test VALUES ('X-Men', 'X-Force', 36153);
INSERT INTO marveledges_test VALUES ('X-Men', 'Deadpool', 36153);
INSERT INTO marveledges_test VALUES ('X-Men', 'Apocalypse', 36153);
INSERT INTO marveledges_test VALUES ('X-Men', 'Deathlok', 36153);
INSERT INTO marveledges_test VALUES ('Death', 'Force', 36153);
INSERT INTO marveledges_test VALUES ('Death', 'Wolverine', 36153);
INSERT INTO marveledges_test VALUES ('Death', 'X-Force', 36153);
INSERT INTO marveledges_test VALUES ('Death', 'Deadpool', 36153);
INSERT INTO marveledges_test VALUES ('Death', 'Apocalypse', 36153);
INSERT INTO marveledges_test VALUES ('Death', 'Deathlok', 36153);
INSERT INTO marveledges_test VALUES ('Force', 'Wolverine', 36153);
INSERT INTO marveledges_test VALUES ('Force', 'X-Force', 36153);
INSERT INTO marveledges_test VALUES ('Force', 'Deadpool', 36153);
INSERT INTO marveledges_test VALUES ('Force', 'Apocalypse', 36153);
INSERT INTO marveledges_test VALUES ('Force', 'Deathlok', 36153);
INSERT INTO marveledges_test VALUES ('Wolverine', 'X-Force', 36153);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Deadpool', 36153);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Apocalypse', 36153);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Deathlok', 36153);
INSERT INTO marveledges_test VALUES ('X-Force', 'Deadpool', 36153);
INSERT INTO marveledges_test VALUES ('X-Force', 'Apocalypse', 36153);
INSERT INTO marveledges_test VALUES ('X-Force', 'Deathlok', 36153);
INSERT INTO marveledges_test VALUES ('Deadpool', 'Apocalypse', 36153);
INSERT INTO marveledges_test VALUES ('Deadpool', 'Deathlok', 36153);
INSERT INTO marveledges_test VALUES ('Apocalypse', 'Deathlok', 36153);
INSERT INTO marveledges_test VALUES ('Ronan', 'Thing', 38608);
INSERT INTO marveledges_test VALUES ('X-Men', 'War Machine', 38082);
INSERT INTO marveledges_test VALUES ('X-Men', 'Havok', 38100);
INSERT INTO marveledges_test VALUES ('X-Men', 'Magneto', 38100);
INSERT INTO marveledges_test VALUES ('X-Men', 'Rogue', 38100);
INSERT INTO marveledges_test VALUES ('X-Men', 'Polaris', 38100);
INSERT INTO marveledges_test VALUES ('X-Men', 'Gambit', 38100);
INSERT INTO marveledges_test VALUES ('Havok', 'Magneto', 38100);
INSERT INTO marveledges_test VALUES ('Havok', 'Rogue', 38100);
INSERT INTO marveledges_test VALUES ('Havok', 'Polaris', 38100);
INSERT INTO marveledges_test VALUES ('Havok', 'Gambit', 38100);
INSERT INTO marveledges_test VALUES ('Magneto', 'Rogue', 38100);
INSERT INTO marveledges_test VALUES ('Magneto', 'Polaris', 38100);
INSERT INTO marveledges_test VALUES ('Magneto', 'Gambit', 38100);
INSERT INTO marveledges_test VALUES ('Rogue', 'Polaris', 38100);
INSERT INTO marveledges_test VALUES ('Rogue', 'Gambit', 38100);
INSERT INTO marveledges_test VALUES ('Polaris', 'Gambit', 38100);
INSERT INTO marveledges_test VALUES ('X-Men', 'Doctor Doom', 38083);
INSERT INTO marveledges_test VALUES ('X-Men', 'Emma Frost', 38083);
INSERT INTO marveledges_test VALUES ('X-Men', 'Magneto', 38083);
INSERT INTO marveledges_test VALUES ('X-Men', 'Wolverine', 38083);
INSERT INTO marveledges_test VALUES ('X-Men', 'Thing', 38083);
INSERT INTO marveledges_test VALUES ('X-Men', 'Cyclops', 38083);
INSERT INTO marveledges_test VALUES ('X-Men', 'Invisible Woman', 38083);
INSERT INTO marveledges_test VALUES ('Doctor Doom', 'Emma Frost', 38083);
INSERT INTO marveledges_test VALUES ('Doctor Doom', 'Magneto', 38083);
INSERT INTO marveledges_test VALUES ('Doctor Doom', 'Wolverine', 38083);
INSERT INTO marveledges_test VALUES ('Doctor Doom', 'Thing', 38083);
INSERT INTO marveledges_test VALUES ('Doctor Doom', 'Cyclops', 38083);
INSERT INTO marveledges_test VALUES ('Doctor Doom', 'Invisible Woman', 38083);
INSERT INTO marveledges_test VALUES ('Emma Frost', 'Magneto', 38083);
INSERT INTO marveledges_test VALUES ('Emma Frost', 'Wolverine', 38083);
INSERT INTO marveledges_test VALUES ('Emma Frost', 'Thing', 38083);
INSERT INTO marveledges_test VALUES ('Emma Frost', 'Cyclops', 38083);
INSERT INTO marveledges_test VALUES ('Emma Frost', 'Invisible Woman', 38083);
INSERT INTO marveledges_test VALUES ('Magneto', 'Wolverine', 38083);
INSERT INTO marveledges_test VALUES ('Magneto', 'Thing', 38083);
INSERT INTO marveledges_test VALUES ('Magneto', 'Cyclops', 38083);
INSERT INTO marveledges_test VALUES ('Magneto', 'Invisible Woman', 38083);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Thing', 38083);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Cyclops', 38083);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Invisible Woman', 38083);
INSERT INTO marveledges_test VALUES ('Thing', 'Cyclops', 38083);
INSERT INTO marveledges_test VALUES ('Thing', 'Invisible Woman', 38083);
INSERT INTO marveledges_test VALUES ('Cyclops', 'Invisible Woman', 38083);
INSERT INTO marveledges_test VALUES ('Wolverine', 'Iron Man', 36469);
INSERT INTO marveledges_test VALUES ('Rogue', 'X-Men', 38101);
INSERT INTO marveledges_test VALUES ('Rogue', 'Polaris', 38101);
INSERT INTO marveledges_test VALUES ('Rogue', 'Havok', 38101);
INSERT INTO marveledges_test VALUES ('X-Men', 'Polaris', 38101);
INSERT INTO marveledges_test VALUES ('X-Men', 'Havok', 38101);
INSERT INTO marveledges_test VALUES ('Polaris', 'Havok', 38101);
INSERT INTO marveledges_test VALUES ('X-Men', 'Cyclops', 39318);
INSERT INTO marveledges_test VALUES ('X-Men', 'Storm', 39318);
INSERT INTO marveledges_test VALUES ('Cyclops', 'Storm', 39318);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Spider-Man', 41351);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Taskmaster', 41351);
INSERT INTO marveledges_test VALUES ('Hawkeye', 'Captain America', 41351);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Taskmaster', 41351);
INSERT INTO marveledges_test VALUES ('Spider-Man', 'Captain America', 41351);
INSERT INTO marveledges_test VALUES ('Taskmaster', 'Captain America', 41351);
